image: python:latest

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt

stages:
  - test
  - style
  
testing:
  stage: test
  script:
    - python manage.py migrate
    - python manage.py test
  
pylint: 
  stage: style
  script:
    - pylint -j 0 --load-plugins=pylint_django Powerbank/ sharing/
  
pep8:
  stage: style
  script:
    - pycodestyle .
