image: python:latest

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt

stages:
  - test
  - style
  
testing:
  stage: test
  script:
    - python manage.py migrate
    - python manage.py test

coverage:
  stage: test
  script:
  - coverage run manage.py test
  - coverage report --omit=manage.py
  - coverage html --omit=manage.py
  - mkdir public
  - mv htmlcov public/coverage
  artifacts:
    paths:
      - public/coverage  
  
pylint: 
  stage: style
  script:
    - pylint -j 0 --load-plugins=pylint_django power_bank/ sharing/
  
pep8:
  stage: style
  script:
    - pycodestyle .
