# Generated by Django 2.1.3 on 2019-03-26 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Powerbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('value', models.IntegerField()),
                ('location', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, null=True)),
                ('active_mail', models.BooleanField(default=False)),
                ('photo', models.FileField(upload_to='users/')),
                ('passport', models.FileField(upload_to='passports/')),
                ('passport_status', models.CharField(default='empty', max_length=216)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('crds_lot', models.FloatField()),
                ('crds_lat', models.FloatField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
