# Generated by Django 2.1.3 on 2019-05-06 19:34

from django.db import migrations, models
from django.db.models.deletion import SET_NULL, SET_DEFAULT, CASCADE
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_share',
            field=models.ForeignKey(null=True,
                                    on_delete=SET_NULL,
                                    related_name='end_share',
                                    to='sharing.Share'),
        ),
        migrations.AddField(
            model_name='order',
            name='end_timestamp',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
