# Generated by Django 2.1.3 on 2019-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
