# Generated by Django 2.1.3 on 2019-04-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_status',
            field=models.CharField(default='inactive', max_length=256),
        ),
        migrations.AddField(
            model_name='share',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=256),
        ),
        migrations.AddField(
            model_name='share',
            name='qrcode',
            field=models.CharField(default='Hello, world!', max_length=512),
        ),
    ]
