# Generated by Django 2.1.7 on 2019-04-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbank',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Share'),
        ),
    ]
