# Generated by Django 2.1.3 on 2019-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20190310_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='time',
            field=models.TimeField(),
        ),
    ]
