# Generated by Django 2.1.7 on 2019-04-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20190405_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbank',
            name='location',
            field=models.IntegerField(),
        ),
    ]
