# Generated by Django 2.1.3 on 2019-05-13 09:28

from django.db import migrations, models
import django.db.models.deletion
from django.db.models.deletion import SET_NULL, SET_DEFAULT, CASCADE


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20190506_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='payment_plans',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wallets',
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_plan',
            field=models.ForeignKey(null=True,
                                    on_delete=SET_NULL,
                                    to='sharing.PaymentPlan'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='description',
            field=models.CharField(default='Самая обычная подписка.',
                                   max_length=512),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='name',
            field=models.CharField(default='Обычная', max_length=128),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
