# Generated by Django 2.1.3 on 2019-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active_mail',
            field=models.BooleanField(default=False),
        ),
    ]
