# Generated by Django 2.1.3 on 2019-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_auto_20190406_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='has_pb',
            field=models.BooleanField(default=False),
        ),
    ]
