# Generated by Django 2.1.3 on 2019-04-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_share_has_pb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(default='hold', max_length=128)),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='powerbank',
            old_name='value',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='powerbank',
            name='is_held',
        ),
        migrations.AddField(
            model_name='order',
            name='pb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.Powerbank'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.Share'),
        ),
    ]
