# Generated by Django 2.1.3 on 2019-04-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_auto_20190410_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='has_pb',
        ),
        migrations.AddField(
            model_name='share',
            name='free_pbs',
            field=models.IntegerField(default=False),
        ),
    ]
