# Generated by Django 2.1.3 on 2019-05-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_remove_powerbank_code'),
        ('sharing', '0005_auto_20190515_2114'),
    ]

    operations = [
    ]
