# Generated by Django 2.1.3 on 2019-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_merge_20190518_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuery',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('share_id', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending',
                                            max_length=128)),
            ],
        ),
    ]
