# Generated by Django 2.1.3 on 2019-04-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_auto_20190410_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.CharField(default='created', max_length=128),
        ),
    ]
