# Generated by Django 2.1.3 on 2019-04-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_order_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='session_status',
        ),
    ]
