# Generated by Django 2.1.3 on 2019-04-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_remove_profile_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation_time',
            field=models.IntegerField(default=15),
        ),
    ]
