# Generated by Django 2.1.3 on 2019-04-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0010_auto_20190411_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Обычный', max_length=128)),
                ('description', models.CharField(default='Самый обычный тариф.', max_length=512)),
                ('payment_type', models.CharField(default='perminute', max_length=128)),
                ('cost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(default='active', max_length=128)),
                ('payment_method', models.CharField(default='promo', max_length=128)),
            ],
        ),
    ]
