# Generated by Django 2.1.3 on 2019-04-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0011_paymentplan_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_plans',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallets',
            field=models.CharField(default='', max_length=512),
        ),
    ]
