# Generated by Django 2.1.3 on 2019-04-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0012_auto_20190415_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.PaymentPlan'),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.Wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Кошелёк', max_length=128),
        ),
    ]
